theme: jekyll-theme-architect

# Site Settings
locale                    : "fa-IR"
title                     : "Scientific Python"
name                      : "سعید محققی Saeed Mohagheghi"

description               : "آموزش پایتون برای برنامه نویسی علمی"
show_downloads            : true
